#!/bin/bash

sudo su
cd /opt

# 1. Install Java and other pre-requisits
yum -y install unzip wget tree git
wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
yum install jdk-8u131-linux-x64.rpm -y

# 2. Add Jenkins Repository and  Install
rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
cd /etc/yum.repos.d/
curl -O https://pkg.jenkins.io/redhat-stable/jenkins.repo
yum -y install jenkins
systemctl start jenkins
systemctl enable jenkins
systemctl status jenkins

#3. Access key to unlock Jenkins UI
/var/lib/jenkins/secrets/initialAdminPassword

paste result in Jenkins UI

#4 Accept default plugins

#5 create admin account, save and continue

